

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'do you like <a href="https://redheads.dev/">redheads</a>?'

style: hacker
listen_for_clients_preferred_style: true 

plugins:
  - jekyll-seo-tag
