title: 'Juliya Gannon'
description: "Full-stack Web Developer"
url: "https://mothralady.github.io"

google_analytics: G-5PKJ4J6H0D

header_pages:
  - index.md
  - about.md

style: hacker

footer: 'do you like <a href="https://github.com/redheadsatx">redheads</a>?'

plugins:
  - jekyll-seo-tag

# Build Settings
markdown: kramdown